type weatherProps =
    'thunderstorm with light rain' | 'thunderstorm with rain'

export function Translate(description: weatherProps) {
    const weather = {
        'thunderstorm with light rain': 'Trovoada com chuva fraca',
        'thunderstorm with rain': 'Trovoada com chuva',
        'thunderstorm with heavy rain': 'Trovoada com chuva forte',
        'light thunderstorm': 'Trovoada leve',
        'thunderstorm': 'Trovoada',
        'heavy thunderstorm': 'Forte tempestade',
        'ragged thunderstorm': 'Tempestade irregular',
        'thunderstorm with light drizzle': 'Trovoada com leve garoa',
        'thunderstorm with drizzle': 'Trovoada com garoa',
        'thunderstorm with heavy drizzle': 'Trovoada com forte garoa',
        'light intensity drizzle': 'Chuvisco com relâmpagos',
        'drizzle': 'Garoa',
        'heavy intensity drizzle': 'Chuvisco de forte intensidade',
        'light intensity drizzle rain': 'Chuvisco com relâmpagos intensos',
        'drizzle rain': 'Chuva torrencial',
        'heavy intensity drizzle rain': 'Chuva forte com garoa',
        'shower rain and drizzle': 'Chuva leve e chuvisco',
        'heavy shower rain and drizzle': 'Chuva forte e garoa',
        'shower drizzle': 'Chuvisco leve',
        'light rain': 'Chuva leve',
        'moderate rain': 'Chuva moderada',
        'heavy intensity rain': 'Chuva de forte intensidade',
        'very heavy rain': 'Chuva muito forte',
        'extreme rain': 'Chuva extrema',
        'freezing rain': 'Chuva congelante',
        'light intensity shower rain': 'Chuva com relâmpago',
        'shower rain': 'Chuvisco',
        'heavy intensity shower rain': 'Chuva forte',
        'ragged shower rain': 'Chuva irregular',
        'light snow': 'Pouca neve',
        'snow': 'Neve',
        'heavy snow': 'Neve pesada',
        'sleet': 'Granizo',
        'light shower sleet': 'Chuva leve com granizo',
        'shower sleet': 'Pouco granizo',
        'light rain and snow': 'Chuva fraca e neve',
        'rain and snow': 'Chuva e neve',
        'light shower snow': 'Chuva de neve fraca',
        'shower snow': 'Nevasca rápida',
        'heavy shower snow': 'Nevasca',
        'mist': 'Névoa',
        'smoke': 'Neblina',
        'haze': 'Neblina',
        'sand/dust whirls': 'Redemoinhos de areia',
        'fog': 'Névoa',
        'sand': 'Areia alta',
        'dust': 'Poeira alta',
        'volcanic ash': 'Cinza vulcanica',
        'squalls': 'Rajadas de vento',
        'tornado': 'Tornado',
        'clear sky': 'Céu limpo',
        'few clouds': 'Poucas nuvens',
        'scattered clouds': 'scattered clouds',
        'broken clouds': 'Nuvens quebradiças',
        'overcast clouds': 'Nuvens nubladas',
    }

    return weather[description] ?? null;
}
